[project]
name = "vincentpy"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.2",
    "langchain>=1.0.8",
    "langchain-openai",
    "polars",
    "pyarrow",
    "pydantic>=2.0.0",
]
